milk:
  unit_price: 3.97
  sale: true
  sale_quantity: 2
  sale_price: 5
bread:
  unit_price: 2.17
  sale: true
  sale_quantity: 3
  sale_price: 6
banana:
  unit_price: 0.99
  sale: false
  sale_quantity: 1
  sale_price: 0
apple:
  unit_price: 0.89
  sale: false
  sale_quantity: 1
  sale_price: 0